# Generated by Django 4.2.3 on 2023-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher_detail_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='teacher_imgs/'),
        ),
    ]
