# Generated by Django 4.2.3 on 2023-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_studentcourseenrollmen_studentcourseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='enrolled_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
