# Generated by Django 4.2.3 on 2023-10-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Course Rating'},
        ),
    ]
