# Generated by Django 4.2.3 on 2023-10-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_notification_notif_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifiread_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
