# Generated by Django 4.2.3 on 2023-10-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_notification_notifiread_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifiread_status',
            new_name='notifread_status',
        ),
    ]
