# Generated by Django 4.2.3 on 2023-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_attempquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempquiz',
            name='right_ans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
