# Generated by Django 4.2.3 on 2023-10-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_attempquiz_right_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempquiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
        ),
    ]
