# Generated by Django 4.2.3 on 2023-10-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_student_otp_digit_student_verify_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verify_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='verify_status',
        ),
    ]
